name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake-ui.svg?color_snake=%230A84FF&color_background=%23ffffff&color_dots=%23E7EEF7,%23B7D6F6,%2383BAF0,%234E9DE9,%231F7BD9
            dist/github-contribution-grid-snake-ui-dark.svg?color_snake=%2300C2FF&color_background=%23161b22&color_dots=%23151D2A,%230F2A47,%23123B62,%23154C7D,%231E82DE

      - name: Push snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
